### ISSUE TITLE
Module doesn't work

### ISSUE THREAD

**Issue by LucaT-PxD** [Bifrost-Technologies/Solana-UnrealEngine5-SDK#1]
Once the plugin is installed and compiled, I received the error:
![image](https://github.com/Bifrost-Technologies/Solana-Unreal-SDK/assets/36664698/775b8c03-ca08-4aa0-a052-5af50627e4bd)
What's wrong?

**Comment by BifrostTitan** [comment]
New release coming in a few hours with fixes to UnrealCLR for 5.3

**Comment by LucaT-PxD** [comment]
It was on UE 5.2, could it works?

**Comment by BifrostTitan** [comment]
Try now. I fixed everything

**Comment by LucaT-PxD** [comment]
Are you interested in a job opportunity? All remotely

**Comment by BifrostTitan** [comment]
Nah but if you need something built by Bifrost Inc. Feel free to message me on X/Twitter if you want discuss a development contract

**Comment by LucaT-PxD** [comment]
Hello, now it is opened but there isn't a demo map inside, is this an error? I can't see the map you are referring in the guide

**Comment by BifrostTitan** [comment]
enable plugin folders on the content browser. its inside the SolanaSDK plugin folder under maps in the content folder. It will not be visible in the projects content folder automatically. I will update the guide to match the new plugin setup
